-- Pre-seed data for demo purposes

-- 1. Seed companies
INSERT INTO companies (id, company_name, domain, industry, company_size, headquarters_location, source_type, culture_tags_json, interview_style_json, fresher_friendly, public_hiring_email) VALUES
('1a2b3c4d-5e6f-7a8b-9c0d-1e2f3a4b5c6d', 'Stripe', 'stripe.com', 'Fintech', 'large', 'San Francisco, CA', 'manual', '["engineering-first", "documentation-driven", "remote-friendly", "high-quality-code"]', '{"rounds": 4, "types": ["coding", "system-design", "behavioral", "practical-bug-hunt"], "difficulty": "hard"}', true, 'hiring@stripe.com'),
('2b3c4d5e-6f7a-8b9c-0d1e-2f3a4b5c6d7e', 'Cloudflare', 'cloudflare.com', 'Cybersecurity', 'large', 'San Francisco, CA', 'manual', '["engineering-led", "open-source-friendly", "hybrid", "highly-technical"]', '{"rounds": 3, "types": ["coding", "systems-networking", "behavioral"], "difficulty": "medium"}', true, 'jobs@cloudflare.com'),
('3c4d5e6f-7a8b-9c0d-1e2f-3a4b5c6d7e8f', 'Vercel', 'vercel.com', 'Cloud Infrastructure', 'mid', 'New York, NY', 'manual', '["remote-first", "fast-paced", "design-focused", "open-source"]', '{"rounds": 4, "types": ["coding-ui", "take-home", "behavioral"], "difficulty": "medium"}', true, 'careers@vercel.com'),
('4d5e6f7a-8b9c-0d1e-2f3a-4b5c6d7e8f9a', 'Razorpay', 'razorpay.com', 'Fintech', 'large', 'Bangalore, India', 'manual', '["fast-growing", "customer-centric", "collaborative", "high-ownership"]', '{"rounds": 4, "types": ["dsa", "machine-coding", "system-design", "bar-raiser"], "difficulty": "hard"}', true, 'freshers@razorpay.com'),
('5e6f7a8b-9c0d-1e2f-3a4b-5c6d7e8f9a0b', 'Postman', 'postman.com', 'DevTools', 'large', 'Bangalore, India', 'manual', '["product-focused", "flexible", "global", "api-first"]', '{"rounds": 3, "types": ["dsa", "machine-coding", "managerial"], "difficulty": "medium"}', true, 'careers@postman.com');

-- 2. Seed source feeds
INSERT INTO source_feeds (source_name, source_type, source_url, trust_level, fetch_frequency) VALUES
('Stripe Greenhouse Board', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/stripe/jobs', 'high', 'daily'),
('Cloudflare Greenhouse Board', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/cloudflare/jobs', 'high', 'daily'),
('Vercel Greenhouse Board', 'greenhouse', 'https://boards-api.greenhouse.io/v1/boards/vercel/jobs', 'high', 'daily'),
('SimplifyJobs New Grad List', 'github', 'https://api.github.com/repos/SimplifyJobs/New-Grad-Positions/contents/README.md', 'medium', 'daily'),
('SimplifyJobs Internship List', 'github', 'https://api.github.com/repos/SimplifyJobs/Summer2025-Internships/contents/README.md', 'medium', 'daily'),
('Stripe Engineering RSS', 'rss', 'https://engineering.stripe.com/feed', 'medium', 'daily'),
('Cloudflare Blog RSS', 'rss', 'https://blog.cloudflare.com/rss', 'medium', 'daily');

-- 3. Seed some sample interview questions
INSERT INTO interview_questions (company_id, role_type, question_text, question_type, difficulty_level, source, source_url, confidence_score) VALUES
('1a2b3c4d-5e6f-7a8b-9c0d-1e2f3a4b5c6d', 'backend', 'Implement a rate limiter in memory supporting token bucket algorithm for API endpoints.', 'coding', 'medium', 'hn', 'https://news.ycombinator.com', 0.80),
('1a2b3c4d-5e6f-7a8b-9c0d-1e2f3a4b5c6d', 'backend', 'Find bugs and write unit tests for a pre-written micro-service representing a payment ledger.', 'coding', 'hard', 'github', 'https://github.com', 0.90),
('2b3c4d5e-6f7a-8b9c-0d1e-2f3a4b5c6d7e', 'backend', 'Explain what happens when you type stripe.com in a web browser and hit enter.', 'system-design', 'medium', 'manual', NULL, 0.95),
('4d5e6f7a-8b9c-0d1e-2f3a-4b5c6d7e8f9a', 'backend', 'Design a simplified parking lot system. Provide low-level design class diagrams and write working code in 90 minutes.', 'coding', 'hard', 'manual', NULL, 0.90),
('3c4d5e6f-7a8b-9c0d-1e2f-3a4b5c6d7e8f', 'frontend', 'Build a simple drag-and-drop file uploader using custom React hooks and style it with Tailwind.', 'coding', 'medium', 'github', NULL, 0.85);

-- 4. Seed hiring notes
INSERT INTO hiring_notes (company_id, note_type, note_text, source, confidence_score) VALUES
('1a2b3c4d-5e6f-7a8b-9c0d-1e2f3a4b5c6d', 'process', 'Stripe conducts a unique "bug hunt" interview round where you are given an existing repository with failing tests or design issues and you must debug it.', 'manual', 0.95),
('4d5e6f7a-8b9c-0d1e-2f3a-4b5c6d7e8f9a', 'process', 'Razorpay focuses heavily on machine coding. They look for clean, modular, and runnable code with OOP principles rather than just basic algorithmic correctness.', 'manual', 0.95);

-- 5. Seed admin user
-- password: AdminPassword123 (using a common bcrypt hash for demo convenience)
-- Hash generated by bcrypt.hashpw(b"AdminPassword123", bcrypt.gensalt(12))
INSERT INTO admin_users (name, email, password_hash, role) VALUES
('Super Admin', 'admin@jobintel.com', '$2b$12$R9h/lIPzMRF.FbeNf3Y.OOoUa66YqW2xUa3X8O.U0LgejZ7a2xLw6', 'superadmin');
